/** Story IDs from docs/stories.md, so screens can say which stories they deliver. */
export type Priority = 'Must' | 'Should' | 'Could'
export interface Story { id: string; title: string; priority: Priority }

export const STORIES: Record<string, Story> = Object.fromEntries(
  (
    [
      ['FAM-1', 'Parent creates a family', 'Must'],
      ['FAM-2', 'Parent adds a student', 'Must'],
      ['FAM-3', 'Second parent joins by invite', 'Should'],
      ['FAM-4', 'Remove a family member', 'Should'],
      ['FAM-5', 'Student changes their own settings', 'Could'],
      ['LRN-1', 'Browse a subject by unit and topic', 'Must'],
      ['LRN-2', 'Work through a stepped lesson', 'Must'],
      ['LRN-3', 'Always have a next step', 'Must'],
      ['LRN-4', 'Set exam dates', 'Should'],
      ['LRN-5', 'Read the subject exam technique guide', 'Must'],
      ['LRN-6', 'Target grade per subject', 'Must'],
      ['LRN-7', 'Interactive lesson steps', 'Must'],
      ['WKS-1', 'Open a worksheet at a chosen level', 'Must'],
      ['WKS-2', 'Print a worksheet and its answers', 'Should'],
      ['WKS-3', 'Self-mark and record a score', 'Must'],
      ['WKS-4', 'Mixed-topic worksheet', 'Should'],
      ['WKS-5', 'Timed paper mode', 'Could'],
      ['WKS-6', 'Grade 9 problem set per unit', 'Should'],
      ['WKS-7', 'Work a worksheet on-screen with a scratch canvas', 'Must'],
      ['QZ-1', 'Take an auto-marked topic quiz', 'Must'],
      ['QZ-2', 'Self-assess an extended response', 'Must'],
      ['QZ-3', 'Spaced recap quiz', 'Should'],
      ['QZ-4', 'Wrong-answer bank', 'Should'],
      ['PRG-1', 'Topic map with status', 'Must'],
      ['PRG-2', 'Recent activity and streak', 'Should'],
      ['PAR-1', 'Weekly summary per child', 'Must'],
      ['PAR-2', "Read-only view of the child's topic map", 'Must'],
      ['PAR-3', 'Weekly email digest', 'Should'],
      ['PAR-4', 'Suggest a task to my child', 'Should'],
      ['PAR-5', 'Eight-week trend', 'Should'],
      ['TUT-1', 'Parent links a tutor to a child', 'Should'],
      ['TUT-2', 'Tutor dashboard across students', 'Should'],
      ['TUT-3', 'Assign a task with a due date', 'Should'],
      ['TUT-4', 'Tutor notes on a student', 'Could'],
      ['MOT-1', 'Points and subject levels', 'Must'],
      ['MOT-2', 'Badges for learning events', 'Should'],
      ['MOT-3', 'Weekly goal ring', 'Must'],
      ['MOT-4', 'Celebrate a milestone', 'Should'],
      ['MOT-5', 'Choose from three tasks', 'Must'],
      ['ADM-1', 'Author a topic with all five parts', 'Must'],
      ['ADM-2', 'Question bank with tags', 'Must'],
      ['ADM-3', 'Review before publish', 'Should'],
      ['ADM-4', 'Report a mistake in content', 'Should'],
      ['ADM-5', 'Bulk import questions', 'Should'],
      ['ADM-6', 'Draft a topic with AI', 'Must'],
      ['ADM-7', 'Generate questions into the bank', 'Should'],
    ] as const
  ).map(([id, title, priority]) => [id, { id, title, priority }]),
)
